spring:
  datasource:
    url: jdbc:mysql://gz-cdb-oamjd7cp.sql.tencentcdb.com:63242/ag_zipkin?useUnicode=true&characterEncoding=UTF8&autoReconnect=true
    username: root
    password: axJkamsUdvF3
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true
  application:
    name: trace
   #zipkin数据保存到数据库中需要进行如下配置
   #表示当前程序不使用sleuth
  sleuth:
    enabled: false
   #表示zipkin数据存储方式是mysql

zipkin:
  storage:
    type: mysql
  collector:
    rabbitmq:
#      addresses: ${RABBIT_MQ_HOST:172.17.0.1}
      addresses: ${RABBIT_MQ_HOST:localhost}
      port: ${RABBIT_MQ_PORT:5672}
      username: lovedrose
      password: love100200
      queue: zipkin
server:
  port: 9411

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
