version: '2'
services:
  register-center:
    image: sc/register-center
    container_name: register-center
    ports:
      - "8761:8761"
  rabbit:
      container_name: rabbitmq
      image: rabbitmq:management
      ports:
       - "4369:4369"
       - "5671:5671"
       - "5672:5672"
       - "15672:15672"
  auth-server:
    image: sc/auth-server
    container_name: auth-server
    ports:
      - "9777:9777"
    depends_on:
      - register-center
    environment:
      - EUREKA_HOST=register-center
      - EUREKA_PORT=8761
      - REDIS_HOST=redis
      - REDIS_PORT=6379
#      - MYSQL_HOST=localhost
#      - MYSQL_PORT=3306
#      - RABBIT_MQ_HOST=rabbitmq
#      - RABBIT_MQ_HOST=5672
  web-admin:
    image: sc/web-admin
    container_name: web-admin
    ports:
      - "8762:8762"
    links:
      - auth-server
    entrypoint: ./wait-for-it.sh auth-server:9777 -t 100 --
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    environment:
      - EUREKA_HOST=register-center
      - EUREKA_PORT=8761
      - REDIS_HOST=redis
      - REDIS_PORT=6379
#      - MYSQL_HOST=localhost
#      - MYSQL_PORT=3306
#      - RABBIT_MQ_HOST=rabbitmq
#      - RABBIT_MQ_HOST=5672
  gateway-server:
    image: sc/gateway-server
    container_name: gateway-server
    ports:
      - "8765:8765"
    links:
      - auth-server
    entrypoint: ./wait-for-it.sh ace-auth:9777 -t 100 --
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    environment:
      - EUREKA_HOST=register-center
      - EUREKA_PORT=8761
#      - RABBIT_MQ_HOST=rabbitmq
#      - RABBIT_MQ_HOST=5672
  redis:
         image: redis
         container_name: redis
         restart: always
         ports:
           - "6379:6379"
         volumes:
           - ./.docker/redis:/var/lib/redis
  tool:
    image: sc/tool
    container_name: tool
    ports:
      - "9992:9992"
    depends_on:
      - register-center
    environment:
      - EUREKA_HOST=register-center
      - EUREKA_PORT=8761

