version: '2'
services:
  register-center:
    image: sc/register-center
    container_name: register-center
    ports:
      - "8761:8761"
  trace:
    image: sc/trace
    container_name: trace
    ports:
      - "9411:9411"
    depends_on:
      - register-center

  auth-server:
    image: sc/auth-server
    container_name: auth-server
    ports:
      - "9777:9777"
    depends_on:
      - register-center
    environment:
      - EUREKA_HOST=register-center
      - EUREKA_PORT=8761
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  web-admin:
    image: sc/web-admin
    container_name: web-admin
    ports:
      - "8762:8762"
    links:
      - auth-server
    entrypoint: ./wait-for-it.sh auth-server:9777 -t 600 --
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    environment:
      - EUREKA_HOST=register-center
      - EUREKA_PORT=8761
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  gateway-server:
    image: sc/gateway-server
    container_name: gateway-server
    ports:
      - "8765:8765"
    links:
      - auth-server
    entrypoint: ./wait-for-it.sh auth-server:9777 -t 600 --
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    environment:
      - EUREKA_HOST=register-center
      - EUREKA_PORT=8761
#  tool:
#    image: sc/tool
#    container_name: tool
#    ports:
#      - "9992:9992"
#    depends_on:
#      - register-center
#    environment:
#      - EUREKA_HOST=register-center
#      - EUREKA_PORT=8761
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis:/var/lib/redis

