spring:
    application:
        name: monitor

server:
    port: 8764 #启动端口

eureka:
     instance:
        ip-address: 127.0.0.1
        prefer-ip-address: true
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

management:
  security:
    enabled: false
