<<<<<<< HEAD:control/monitor/src/main/resources/application.yml
spring:
    application:
        name: monitor
    boot:
        admin:
          routes:
            endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
          turbine:
            clusters: jscloud
            location: turbine
server:
    port: 8764 #启动端口

security:
    user:
        name: whb
        password: 123456
        role: USER

eureka:
     instance:
        preferIpAddress: true
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false
=======
spring:
    application:
        name: ace-monitor

server:
    port: 8764 #启动端口

eureka:
     instance:
        preferIpAddress: true
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false
>>>>>>> upstream/master:ace-control/ace-monitor/src/main/resources/application.yml
