spring:
    application:
        name: monitor

server:
    port: 8764 #启动端口

eureka:
     instance:
        ip-address: 192.168.99.100
        prefer-ip-address: true
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://192.168.99.100:8761/eureka/

management:
  security:
    enabled: false
