logging:
    level:
#        tk.mybatis: DEBUG
        com.lovehins: DEBUG
server:
    port: 9992

spring:
    profiles:
      active: dev
    application:
        name: tool
    rabbitmq:
      host: ${RABBIT_MQ_HOST:172.17.0.1}
      port: ${RABBIT_MQ_PORT:5672}
      username: lovedrose
      password: love100200
    sleuth:
        sampler:
            percentage: 1

search:
  lucence:
    path: ./lucence/file

# 具体看类:CloudStorageConfig
oss:
  type: 1 # 类型 1：七牛  2：阿里云  3：腾讯云
  qiniuDomain: https://www.qiniu.com/
  qiniuPrefix: oss
  qiniuAccessKey: U7V8wnNFyCTn2TFn4L1ZCktWA_Yn-OKsebJ8Hr72
  qiniuSecretKey: MmNb5lYg3JPGYnAAg-sCNJkP6qR4I6vwjwIrybX-
  qiniuBucketName: test